core: Fix missing include with gcc6
mediatek/platform/mt6589/kernel/core/core.c:30:30: warning: implicit declaration of function 'IO_VIRT_TO_PHYS' [-Wimplicit-function-declaration]
         .pfn = __phys_to_pfn(IO_VIRT_TO_PHYS(VDEC_GCON_BASE)),
                              ^
/home/pmos/build/src/android_kernel_fairphone_FP1-49779cdc4a689ec332f07764111f4bc9b39e4c32/kernel/arch/arm/include/asm/memory.h:135:48: note: in definition of macro '__phys_to_pfn'
 #define __phys_to_pfn(paddr) ((unsigned long)((paddr) >> PAGE_SHIFT))
                                                ^~~~~
/home/pmos/build/src/android_kernel_fairphone_FP1-49779cdc4a689ec332f07764111f4bc9b39e4c32/kernel/arch/arm/include/asm/memory.h:135:30: error: initializer element is not constant
 #define __phys_to_pfn(paddr) ((unsigned long)((paddr) >> PAGE_SHIFT))
                              ^