dsi_drv: use mdelay instead of udelay
This fixes:

mediatek/platform/mt6589/kernel/drivers/built-in.o: In function `lcm_mdelay':
/mnt/hdd/fairphone/mtk/alps-fairphone-gpl/kernel/mediatek/platform/mt6589/kernel/drivers/video/dsi_drv.c:259: undefined reference to `__bad_udelay'

and makes the kernel compile with arm-linux-androideabi-4.9